@startuml
start
fork
:从省内批量采集实体，导出发布包发送邮件;
:云边导入发布包;
fork again
:执行转换后的 GBASE 建表语句批量建表;
note left
手动登记里面没有这步，因为省内大批量采集导入会报错，
而且效率较低,导入之后就是已提交状态不好改数据周期。
end note
:批量采集所有的实体;
end fork
:运行脚本开始登记所有的实体;
note right: 这边采集出来的实体信息都是默认值。
:读取接口清单;
while (遍历每一个接口)
  :读取该接口下的实体列表;
  while(遍历每个实体)
  :填写实体中文名称;
  :填写业务口径;
  :填写技术口径;
  :填写字段中文名称;
  :填写字段业务口径;
  :填写字段技术口径;
  :填写分区;
  endwhile
endwhile
:HASH主键还无法自动填写，需要自己填写一下，数据周期修改一下;
note right: 这部分的工作不多，因为只有结果表需要做这个操作。
:批量提交;
:发布上线;
stop
@enduml