@startmindmap
'https://plantuml.com/mindmap-diagram

title 实体登记自动化准备材料

* 实体登记自动化
**  [[http://localhost:8081/@fs/D:\workplace\code\opensource\qifan-blog-vuepress2\docs\knowledge\newland\img_8.png 接口任务]]
***_ 脚本提取
**** [[http://localhost:8081/@fs/D:\workplace\code\opensource\qifan-blog-vuepress2\docs\knowledge\newland\img_10.png 接口清单]]
***** 接口编号
***** 接口名称
***** 脚本名称
******_ [[http://localhost:8081/@fs/D:\workplace\code\opensource\qifan-blog-vuepress2\docs\knowledge\newland\img.png 脚本提取]]
******* 实体列表
** [[http://localhost:8081/@fs/D:\workplace\code\opensource\qifan-blog-vuepress2\docs\knowledge\newland\img_9.png 规范手册]]
***_ 脚本提取
**** [[http://localhost:8081/@fs/D:\workplace\code\opensource\qifan-blog-vuepress2\docs\knowledge\newland\img_11.png 接口单元描述]]
** Oracle脚本
***_ [[http://localhost:8081/@fs/D:\workplace\code\opensource\qifan-blog-vuepress2\docs\knowledge\newland\img_12.png 脚本提取]]
**** 技术口径
**  [[http://localhost:8081/@fs/D:\workplace\code\opensource\qifan-blog-vuepress2\docs\knowledge\newland\img_13.png 结果表字段清单]]
** 省内导出所有表的建表语句
***_ 通过转换脚本
**** [[http://localhost:8081/@fs/D:\workplace\code\opensource\qifan-blog-vuepress2\docs\knowledge\newland\img_14.png 转换成GBASE语法建表语句]]


header
My super header
endheader



@endmindmap
