@startuml
start
:oracle原始脚本;

:代码块识别;
note right
[[http://localhost:8081/@fs/D:\workplace\code\opensource\qifan-blog-vuepress2\docs\knowledge\newland\script\img_1.png 正则匹配]]
end note
:V_SQL提取;
note right
[[http://localhost:8081/@fs/D:\workplace\code\opensource\qifan-blog-vuepress2\docs\knowledge\newland\script\img_2.png 正则匹配]]
end note
:注释提取 ;
note right
[[http://localhost:8081/@fs/D:\workplace\code\opensource\qifan-blog-vuepress2\docs\knowledge\newland\script\img_3.png 正则匹配]]
end note
:变量替换;

note right
[[http://localhost:8081/@fs/D:\workplace\code\opensource\qifan-blog-vuepress2\docs\knowledge\newland\script\img_4.png 替换规则]]
end note
:常见语法改造;
note right
比如 alter table  truncate partition
改成 delete from
end note
:校验规则改造;
note right
[[http://localhost:8081/@fs/D:\workplace\code\opensource\qifan-blog-vuepress2\docs\knowledge\newland\script\img_5.png Oracle校验规则]]
[[http://localhost:8081/@fs/D:\workplace\code\opensource\qifan-blog-vuepress2\docs\knowledge\newland\script\img_6.png Gbase校验规则]]
end note
:统一清空稽核表;
stop
@enduml
